# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='filtro',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
